name: Run Tests

on:
  push: {}
  workflow_dispatch: {}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.1.0
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Install Requirements
      run: |
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd deployer
        python ./tests.py